### ISSUE TITLE
Install Docker - older OS or Windows Home editions

### ISSUE THREAD

**Issue by Nomesque** [Magikcraft/magikcraft-builder#1]
Suggested text addition, based on installing the software on a Windows 10 Home machine:

---

If you’re using an older or cut-down operating system – for example, Windows Home - you might need to install Docker Toolbox instead:
1. Download Docker Toolbox from here: https://www.docker.com/products/docker-toolbox
2. Open Docker Quickstart Terminal [note: is the name the same between OSs?] When you start Docker Toolbox for the first time, it will download the default ISO. 

Keep an eye on the output as Docker configures the container. Look for an IP address being set. Copy this IP address to a text file - you'll need it to connect to your new image from Minecraft.

Note: If you receive an error in the terminal saying that you need to turn on VT-x in your BIOS, you’ll need to edit your BIOS settings – Google ‘edit bios’ and the brand of your laptop to figure out how to do this. You might need to:
• Enable Intel Virtualization Technology.
• Disable VT-d.
These settings are usually found in the Advanced section of your BIOS settings.

**Comment by jwulf** [comment]
Thanks, integrated!

**Comment by jwulf** [comment]
http://read.corilla.com/Magikcraftio/Magikcraft-Builder.html#Docker
