### ISSUE TITLE
Get Magikcraft Builder - minor wording changes

### ISSUE THREAD

**Issue by Nomesque** [Magikcraft/magikcraft-builder#2]
**Current text:** With Docker installed on your machine, download the Magikcraft Builder to your machine with the following command:
**Suggested text:** Open Docker. Download the Magikcraft Builder into your Docker container by typing the following command:

**Current text:** You will see output like:
**Suggested text:** If the image has downloaded correctly, the output will look like this:

**Comment by jwulf** [comment]
http://read.corilla.com/Magikcraftio/Magikcraft-Builder.html#Get-Magikcraft-Builder
