### ISSUE TITLE
Start Magikcraft Builder - minor changes

### ISSUE THREAD

**Issue by Nomesque** [Magikcraft/magikcraft-builder#3]
**Current text:** 1. Go to the directory where you created the docker-compose.yml file.
**Suggested text:** 1. Go back to Docker and navigate to the directory in which you saved the docker-compose.yml file.

"The Magikcraft Builder will start, and you will get a long code that is the ID for the Magikcraft Builder."
I didn't see this code until I ran the docker ps -a command.

**Comment by jwulf** [comment]
http://read.corilla.com/Magikcraftio/Magikcraft-Builder.html#Start-Magikcraft-Builder
