### ISSUE TITLE
Connect to Magikcraft Builder - add steps

### ISSUE THREAD

**Issue by Nomesque** [Magikcraft/magikcraft-builder#4]
**Current text:** 
1. Open Minecraft.
2. Add a new server.

**Suggested text:** 
1. Open Minecraft.
2. Select Multiplayer.
3. Click on Add server.

**Current text:** 4. Set the address to 127.0.0.1
[127.0.0.1 didn’t work for me; neither did localhost. I had to use the IP address set by Docker Toolbox: 192.168.99.100. ]
**Suggested text:** 4. Set the address to the IP address allocated to the Docker image. This will typically be a set of four numbers separated by periods, like this: _192.168.0.1_. If you're unsure what the IP address is, try _127.0.0.1_ or _localhost_.

**Comment by jwulf** [comment]
http://read.corilla.com/Magikcraftio/Magikcraft-Builder.html#Connect-to-Magikcraft-Builder
